#!/usr/bin/env python3
"""Render docs/metadata-fields-static.json as human-readable Markdown.

Input: the JSON inventory emitted by tools/inventory_static.py.
Output: docs/metadata-fields.md — one page that lists every Tika metadata
field, grouped by:

    1. Declared properties (in namespace order)
       — fields backed by a Property constant in org.apache.tika.metadata.*
    2. Undeclared string literals (alphabetical)
       — fields emitted by parsers via metadata.set("string-literal", ...)
         without a Property constant. The type-safety leak surface.
    3. Parsers index — for each parser class, the set of fields it emits.

Both sections show:
  - Field name (the canonical string key)
  - Type (Property factory method: internalText, internalBoolean, ...)
  - Declaring class / source location
  - Javadoc (when present on the Property declaration)
  - Which parser classes emit the field

The Markdown is self-contained — no external links beyond GitHub-style
relative source paths.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path


def render(doc: dict) -> str:
    out: list[str] = []
    out.append("# Tika Metadata Field Inventory")
    out.append("")
    out.append(f"Generated by `tools/inventory_static.py` at {doc['scanned_at']}.")
    out.append("")
    out.append(f"- **{doc['summary']['property_declarations']}** declared `Property` constants")
    out.append(f"- **{doc['summary']['parsers_emitting_fields']}** parser classes emit fields")
    out.append(f"- **{doc['summary']['undeclared_string_fields']}** undeclared string-literal fields")
    out.append("  *(parsers emit these without a backing `Property` declaration — the type-safety leak surface)*")
    out.append("")
    out.append("> This file is auto-generated from Tika source. Edit `tools/inventory_static.py` or the source it scans, then rerun. CI snapshots the JSON; PRs that change fields without updating the snapshot fail.")
    out.append("")
    out.append("## Contents")
    out.append("")
    out.append("- [Declared properties (by namespace)](#declared-properties-by-namespace)")
    out.append("- [Undeclared string-literal fields](#undeclared-string-literal-fields)")
    out.append("- [Parsers and what they emit](#parsers-and-what-they-emit)")
    out.append("")

    # ── Declared properties grouped by declaring namespace class ─────────────
    out.append("## Declared properties (by namespace)")
    out.append("")
    by_namespace: dict[str, list[tuple[str, dict]]] = defaultdict(list)
    for name, prop in doc["properties"].items():
        by_namespace[prop["declared_in"]].append((name, prop))

    for namespace in sorted(by_namespace):
        short = namespace.rsplit(".", 1)[-1]
        out.append(f"### `{short}` — `{namespace}`")
        out.append("")
        out.append("| Field | Type | Constant | Emitted by | Javadoc |")
        out.append("|---|---|---|---|---|")
        for name, prop in sorted(by_namespace[namespace]):
            emitters = prop.get("emitted_by", [])
            if emitters:
                # Show count + first 2 short names
                short_names = [e.rsplit(".", 1)[-1] for e in emitters[:2]]
                emitter_cell = ", ".join(short_names)
                if len(emitters) > 2:
                    emitter_cell += f" *(+{len(emitters)-2})*"
            else:
                emitter_cell = "_unused_"
            jd = (prop.get("javadoc") or "").replace("|", "\\|").replace("\n", " ")
            if len(jd) > 100:
                jd = jd[:97] + "..."
            out.append(f"| `{name}` | `{prop['type']}` | `{prop['constant_name']}` | {emitter_cell} | {jd} |")
        out.append("")

    # ── Undeclared string-literal fields ─────────────────────────────────────
    out.append("## Undeclared string-literal fields")
    out.append("")
    out.append("These field names appear in `metadata.set(\"literal\", ...)` calls without a backing `Property` declaration. Each one is a candidate for migration into a namespace file's `Property` constant; until then, downstream consumers have no type info or canonical place to look up the field's meaning.")
    out.append("")
    if not doc["undeclared_string_fields"]:
        out.append("_(none)_")
    else:
        out.append("| Field | Emitter | Source |")
        out.append("|---|---|---|")
        for name in sorted(doc["undeclared_string_fields"]):
            sites = doc["undeclared_string_fields"][name]["emitted_by"]
            for s in sites:
                short = s["class"].rsplit(".", 1)[-1]
                src = f"`{s['file']}:{s['line']}`"
                out.append(f"| `{name}` | `{short}` | {src} |")
    out.append("")

    # ── Parsers and what they emit ───────────────────────────────────────────
    out.append("## Parsers and what they emit")
    out.append("")
    out.append("For each parser class that emits metadata fields, the canonical field names it sets. Useful for tracing extraction provenance: given a field in an output, what parser populated it?")
    out.append("")
    for parser, info in sorted(doc["parsers"].items()):
        short = parser.rsplit(".", 1)[-1]
        out.append(f"### `{short}`")
        out.append(f"*`{parser}`*")
        out.append("")
        for f in info["emits"]:
            out.append(f"- `{f}`")
        out.append("")

    return "\n".join(out)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--inventory", default="docs/metadata-fields-static.json", type=Path,
                    help="Input JSON (default: docs/metadata-fields-static.json)")
    ap.add_argument("--out", default="docs/metadata-fields.md", type=Path,
                    help="Output Markdown (default: docs/metadata-fields.md)")
    args = ap.parse_args(argv)
    if not args.inventory.exists():
        print(f"error: {args.inventory} not found — run tools/inventory_static.py first",
              file=sys.stderr)
        return 2
    doc = json.loads(args.inventory.read_text())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(doc))
    print(f"wrote {args.out} ({args.out.stat().st_size} bytes)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
